<div class="prompt">
    <h1>Essayez Flus gratuitement<br />pendant 1 mois</h1>

    <p>
        puis <?= FreshRSS_Context::$system_conf->billing['month_price'] ?> € par mois
        ou <?= FreshRSS_Context::$system_conf->billing['year_price'] ?> € par an.
    </p>

    <p>
        <a href="<?= _url('auth', 'login') ?>">
            Déjà un compte ? Connectez-vous.
        </a>
    </p>

    <form method="post" action="<?= _url('user', 'create') ?>">
        <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

        <div>
            <label class="group-name" for="new_user_name"><?= _t('gen.auth.username'), '<br />', _i('help'), ' ', _t('gen.auth.username.format') ?></label>
            <input id="new_user_name" name="new_user_name" type="text" size="16" required="required" autocomplete="off" pattern="<?= FreshRSS_user_Controller::USERNAME_PATTERN ?>" />
        </div>

        <?php if ($this->show_email_field) { ?>
            <div>
                <label class="group-name" for="new_user_email">
                    <?= _t('gen.auth.email') ?>
                </label>
                <input id="new_user_email" name="new_user_email" type="email" required />
            </div>
        <?php } ?>

        <div>
            <label class="group-name" for="new_user_passwordPlain"><?= _t('gen.auth.password'), '<br />', _i('help'), ' ', _t('gen.auth.password.format') ?></label>
            <div class="stick">
                <input type="password" id="new_user_passwordPlain" name="new_user_passwordPlain" required="required" autocomplete="new-password" pattern=".{7,}" />
                <a class="btn toggle-password" data-toggle="new_user_passwordPlain"><?= _i('key') ?></a>
            </div>
            <noscript><b><?= _t('gen.js.should_be_activated') ?></b></noscript>
        </div>

        <?php if ($this->show_tos_checkbox) { ?>
            <div>
                <label class="checkbox" for="accept-tos">
                    <input type="checkbox" name="accept_tos" id="accept-tos" value="1" required />
                    <?= _t('gen.auth.accept_tos', _url('index', 'tos')) ?>
                </label>
            </div>
        <?php } ?>

        <div class="prompt-actions">
            <?php
                $redirect_url = urlencode(Minz_Url::display(
                    array('c' => 'index', 'a' => 'index'),
                    'php', true
                ));
            ?>
            <input type="hidden" name="r" value="<?= $redirect_url ?>" />

            <button type="submit" class="btn btn-important">
                Créer le compte
            </button>

            <a href="<?= _url('index', 'index') ?>">
                Retourner à l’accueil
            </a>
        </div>
    </form>
</div>
