<div class="post content">
    <?php if ($this->is_connected) { ?>
        <a href="<?php echo _url('billing', 'renew'); ?>">
            <?php echo _t('gen.action.back'); ?>
        </a>
    <?php } elseif ($this->can_register) { ?>
        <a href="<?php echo _url('auth', 'register'); ?>">
            <?php echo _t('gen.action.back'); ?>
        </a>
    <?php } else { ?>
        <a href="<?php echo _url('index', 'index'); ?>">
            <?php echo _t('gen.action.back'); ?>
        </a>
    <?php } ?>

    <?php echo $this->cgv; ?>
</div>
