<main class="fl-page fl-page-home">
    <section class="fl-section fl-text-container">
        <h1>Flus propose FreshRSS</h1>

        <p class="lead">
            FreshRSS, un agrégateur de flux <abbr>RSS</abbr>, est le service historique proposé par Flus.
        </p>

        <div>
            <?php if ($this->registration_opened) { ?>
                <a class="btn btn-important" href="<?= _url('auth', 'register') ?>">
                    Créez-vous un compte
                </a>

                ou
            <?php } ?>

            <a href="<?= _url('auth', 'login') ?>">connectez-vous</a>
        </div>

        <p>
            Le service est aujourd’hui limité à <?= $this->max_registrations ?> comptes.

            <strong>
                <a href="https://flus.fr">Rendez-vous sur flus.fr</a> pour découvrir la plateforme de veille principale proposée par Flus.
            </strong>
        </p>
    </section>

    <section class="fl-section">
        <img class="illustration" src="<?= $this->illustration_url ?>" alt="" />
    </section>

    <section class="fl-section">
        <h2>Disposez des fonctionnalités dont vous avez besoin pour votre veille</h2>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Abonnez-vous à n’importe quel site</h3>

                <p>
                    En se basant sur les standards <abbr title="Really Simple Syndication">RSS</abbr>
                    et Atom, Flus vous permet de vous connecter à la très vaste
                    majorité des sites d’actualité et des blogs existants.
                </p>
            </div>

            <div class="fl-column">
                <h3>Importez (et exportez) votre liste d’abonnements</h3>

                <p>
                    Si vous utilisez déjà un agrégateur d’actualité, vous
                    pouvez générer un fichier <abbr title="Outline Processor Markup Language">OPML</abbr>
                    et rejoindre Flus en quelques clics. Nous vous permettons
                    également de repartir à tout moment avec vos données.
                </p>
            </div>
        </div>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Gardez une trace de ce que vous souhaitez lire</h3>

                <p>
                    En marquant comme «&nbsp;lus&nbsp;» les articles que vous venez de
                    lire ou en les plaçant dans vos favoris pour les lire plus tard,
                    vous ne risquez pas de passer à côté d’un article intéressant.
            </div>

            <div class="fl-column">
                <h3>Organisez vos sources par catégories</h3>

                <p>
                    Vous pouvez ranger vos sources d’information par catégories
                    afin de parcourir les articles par ordre thématique et
                    retrouver vos sites préférés plus facilement.
                </p>
            </div>
        </div>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Bénéficiez d’une recherche puissante et rapide</h3>

                <p>
                    En quelques secondes, retrouvez un article par un mot dont
                    vous vous souvenez, le nom de son auteur ou encore un tag
                    associé. Chaque recherche peut être sauvegardée pour être
                    réutilisée plus tard.
                </p>
            </div>

            <div class="fl-column">
                <h3>Partagez les articles qui vous interpellent vers les réseaux sociaux</h3>

                <p>
                    Un article vous semble particulièrement intéressant&nbsp;? Flus
                    vous permet de le partager à vos contacts sur Twitter, Facebook,
                    Mastodon et bien d’autres en quelques secondes.
                </p>
            </div>
        </div>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Applications mobile & bureau</h3>

                <p>
                    Vous pouvez vous connecter à Flus avec différentes applications
                    afin de pouvoir lire n’importe où, que ce soit à la maison, au
                    bureau ou dans les transports.
                </p>

                <p>
                    <a href="https://github.com/FreshRSS/FreshRSS#apis--native-apps">Accéder à la liste complète des applications.</a>
                </p>
            </div>

            <div class="fl-column">
            </div>
        </div>
    </section>

    <section class="fl-section">
        <p class="lead center">
            Bien entendu, <strong>rien ni personne n’observe ce que vous lisez</strong>,<br />
            votre vie privée ne regarde que vous.
        </p>
    </section>

    <section class="fl-section fl-section-prices">
        <p class="center">
            <strong>Un prix unique : le vôtre.</strong><br />
            De 0 à 120 €, le prix est libre.
        </p>

        <p class="center">
            <a href="https://flus.fr/tarifs">En apprendre plus sur flus.fr.</a>
        </p>

        <?php if ($this->registration_opened) { ?>
            <p class="center">
                <a class="btn btn-important" href="<?= _url('auth', 'register') ?>">
                    Inscrivez-vous, le 1<sup>er</sup> mois est gratuit
                </a>
            </p>
        <?php } ?>
    </section>

    <section class="fl-section fl-section-freshrss">
        <div class="fl-columns">
            <div class="fl-column">
                <h2>Flus utilise FreshRSS</h2>

                <p>
                    Quoi de mieux pour avoir confiance dans le service utilisé qu’<strong>un
                    logiciel dont le code est ouvert et amélioré par une communauté&nbsp;?</strong>
                </p>

                <p>
                    J’ai fait le choix d’utiliser <a href="https://freshrss.org">FreshRSS</a>
                    qui est une solution facile à prendre en main, solide et
                    efficace. Sa communauté réactive est toujours à l’écoute des
                    suggestions d’amélioration ce qui garantit des évolutions fréquentes.
                </p>
            </div>

            <div class="fl-column fl-column-centered">
                <img class="logo" src="<?= Minz_Url::display('/themes/icons/icon.svg') ?>" />
            </div>
        </div>
    </section>

    <section class="fl-section fl-section-carnet">
        <p class="lead center">
            Vous voulez en savoir plus sur le service&nbsp;?<br />
            <strong><a href="https://flus.fr/carnet/">Rendez-vous sur le blog «&nbsp;carnet de flus&nbsp;»</a></strong>
        </p>
    </section>

    <section class="fl-section fl-text-container">
        <h2>Flus, c’est qui&nbsp;?</h2>

        <p>
            Je suis Marien, ingénieur en informatique vivant à Grenoble.
        </p>

        <p>
            <strong>Je participe depuis maintenant plus de 10 ans à la vaste
                communauté du logiciel libre.</strong> Il s’agit à la fois d’un
            plaisir –&nbsp;celui de partager le fruit de mon travail&nbsp;– et d’un
            engagement. J’ai rejoint pour cela
            <a href="https://framasoft.org/">l’association Framasoft</a> en 2015.
            J’y ai trouvé l’espace nécessaire pour politiser ma vision d’un
            numérique basé sur la notion des communs.
        </p>

        <p>
            <strong>Je crois infiniment que l’on peut imaginer un numérique à
                dimension humaine.</strong> J’ai, comme beaucoup d’entre vous,
            horreur d’avoir affaire à d’énormes services en ligne sans
            visage&nbsp;; mon entreprise n’est pas destinée à grossir indéfiniment
            et je souhaite ainsi garder une taille accessible. N’hésitez pas
            <a href="https://flus.fr/contact">à m’interpeler pour discuter&nbsp;!</a>
        </p>

        <p>
            <strong>Enfin, j’essaye toujours de tenir un discours honnête.</strong>
            Je fais de mon mieux pour établir la confiance, notamment en expliquant
            autant que possible les choix que je fais concernant le service que je
            mets en ligne. C’est pour moi un engagement de respect envers
            vous-mêmes.
        </p>
    </section>
</main>

<footer class="fl-page-footer">
    <p>
        <a href="https://flus.fr/contact">Contact</a>&nbsp;·&nbsp;<a href="https://flus.fr/securite">Sécurité</a>&nbsp;·&nbsp;<a href="https://flus.fr/credits">Crédits</a>&nbsp;·&nbsp;<a href="https://flus.fr/mentions-legales">Mentions légales</a>
    </p>

    <p>
        <a href="https://flus.fr">Accéder à Flus 2</a>&nbsp;·&nbsp;<a href="https://status.flus.fr/">Statut des services</a>
    </p>

    <p class="copyright">
        Licence libre <a href="https://github.com/flusio/FreshRSS/blob/flus/LICENSE.txt">AGPL-3.0</a> (<a href="https://github.com/flusio">code source</a>)
    </p>
</footer>
