<main class="fl-page fl-page-home">
    <section class="fl-section fl-text-container">
        <h1>Suivez l’actualité qui <em>vous</em> intéresse</h1>

        <p class="lead">
            Abonnez-vous aux sites, blogs et podcasts que vous avez l’habitude
            de suivre pour tous les retrouver en un seul endroit.
        </p>

        <?php if ($this->registration_opened) { ?>
            <p class="center">
                <a class="btn btn-important" href="<?= _url('auth', 'register') ?>">
                    Créez-vous un compte
                </a>
            </p>
        <?php } else { ?>
            <p class="center secondary">
                Le service n’est pas encore ouvert.
            </p>
        <?php } ?>

        <p class="center">
            <a href="<?= _url('auth', 'login') ?>">Déjà un compte&nbsp;? Connectez-vous</a>
        </p>
    </section>

    <section class="fl-section">
        <img class="illustration" src="<?= $this->illustration_url ?>" alt="" />
    </section>

    <section class="fl-section">
        <h2>Disposez des fonctionnalités dont vous avez besoin pour votre veille</h2>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Abonnez-vous à n’importe quel site</h3>

                <p>
                    En se basant sur les standards <abbr title="Really Simple Syndication">RSS</abbr>
                    et Atom, Flus vous permet de vous connecter à la très vaste
                    majorité des sites d’actualité et des blogs existants.
                </p>
            </div>

            <div class="fl-column">
                <h3>Importez (et exportez) votre liste d’abonnements</h3>

                <p>
                    Si vous utilisez déjà un agrégateur d’actualité, vous
                    pouvez générer un fichier <abbr title="Outline Processor Markup Language">OPML</abbr>
                    et rejoindre Flus en quelques clics. Nous vous permettons
                    également de repartir à tout moment avec vos données.
                </p>
            </div>
        </div>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Gardez une trace de ce que vous souhaitez lire</h3>

                <p>
                    En marquant comme «&nbsp;lus&nbsp;» les articles que vous venez de
                    lire ou en les plaçant dans vos favoris pour les lire plus tard,
                    vous ne risquez pas de passer à côté d’un article intéressant.
            </div>

            <div class="fl-column">
                <h3>Organisez vos sources par catégories</h3>

                <p>
                    Vous pouvez ranger vos sources d’information par catégories
                    afin de parcourir les articles par ordre thématique et
                    retrouver vos sites préférés plus facilement.
                </p>
            </div>
        </div>

        <div class="fl-columns">
            <div class="fl-column">
                <h3>Bénéficiez d’une recherche puissante et rapide</h3>

                <p>
                    En quelques secondes, retrouvez un article par un mot dont
                    vous vous souvenez, le nom de son auteur ou encore un tag
                    associé. Chaque recherche peut être sauvegardée pour être
                    réutilisée plus tard.
                </p>
            </div>

            <div class="fl-column">
                <h3>Partagez les articles qui vous interpellent vers les réseaux sociaux</h3>

                <p>
                    Un article vous semble particulièrement intéressant&nbsp;? Flus
                    vous permet de le partager à vos contacts sur Twitter, Facebook,
                    Mastodon et bien d’autres en quelques secondes.
                </p>
            </div>
        </div>
    </section>

    <section class="fl-section">
        <p class="lead center">
            Bien entendu, <strong>rien ni personne n’observe ce que vous lisez</strong>,<br />
            votre vie privée ne regarde que vous.
        </p>
    </section>

    <section class="fl-section fl-section-apps">
        <h2>Applications mobile & bureau</h2>

        <div class="fl-text-container">
            <p>
                Vous pouvez vous connecter à Flus avec différentes applications
                afin de pouvoir lire n’importe où, que ce soit à la maison, au
                bureau ou dans les transports.
            </p>

            <p>
                <em>Le code des applications dont le nom est suivi d’un
                astérisque&nbsp;(*) est fermé.</em>
            </p>
        </div>

        <h3>Android</h3>

        <div class="fl-columns">
            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['easyrss'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            EasyRSS
                        </div>
                        <div class="fl-app-links">
                            <a href="https://github.com/Alkarex/EasyRSS">Site officiel</a>
                            –
                            <a href="https://f-droid.org/packages/org.freshrss.easyrss/">F-Droid</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['feedme'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            FeedMe*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://play.google.com/store/apps/details?id=com.seazon.feedme">Google Play</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['readably'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Readably*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://play.google.com/store/apps/details?id=com.isaiasmatewos.readably">Google Play</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <h3>iOS</h3>

        <div class="fl-columns">
            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['reeder-ios'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Reeder*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://www.reederapp.com/">Site officiel</a>
                            –
                            <a href="https://apps.apple.com/us/app/reeder-4/id1449412357?ls=1">App Store</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['fiery-feeds'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Fiery Feeds*
                        </div>
                        <div class="fl-app-links">
                            <a href="http://cocoacake.net/apps/fiery/">Site officiel</a>
                            –
                            <a href="https://apps.apple.com/app/fiery-feeds-rss-reader/id1158763303">App Store</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['unread'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Unread*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://www.goldenhillsoftware.com/unread/">Site officiel</a>
                            –
                            <a href="https://apps.apple.com/app/unread-rss-reader/id1252376153">App Store</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <h3>MacOS</h3>

        <div class="fl-columns">
            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['vienna'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Vienna
                        </div>
                        <div class="fl-app-links">
                            <a href="https://www.vienna-rss.com/">Site officiel</a>
                            –
                            <a href="https://github.com/ViennaRSS/vienna-rss/releases/latest">Téléchargement</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['reeder-macos'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Reeder*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://www.reederapp.com/">Site officiel</a>
                            –
                            <a href="https://itunes.apple.com/us/app/reeder-4/id1449412482?ls=1&mt=12">App Store</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['readkit'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            Readkit*
                        </div>
                        <div class="fl-app-links">
                            <a href="https://readkitapp.com/">Site officiel</a>
                            –
                            <a href="https://apps.apple.com/app/readkit/id588726889?ls=1&mt=12">App Store</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <h3>Gnu/Linux</h3>

        <div class="fl-columns">
            <div class="fl-column">
                <div class="fl-app">
                    <img class="fl-app-icon" src="<?= $this->app_icons['feedreader'] ?>" />
                    <div class="fl-app-details">
                        <div class="fl-app-name">
                            FeedReader
                        </div>
                        <div class="fl-app-links">
                            <a href="https://jangernert.github.io/FeedReader/">Site officiel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="fl-section fl-section-prices">
        <div class="fl-columns">
            <div class="fl-column fl-column-centered">
                <p>
                    <strong><?= $this->month_price ?>&nbsp;€ par mois</strong><br />
                    ou<br />
                    <strong><?= $this->year_price ?>&nbsp;€ par an</strong><br />
                </p>
            </div>

            <div class="fl-column">
                <h2>Des tarifs simples et transparents</h2>

                <p>
                    En vous abonnant à Flus, vous payez un prix unique, au mois
                    ou à l’année. Les tarifs restent identiques, même si vous
                    vous abonnez à de nombreux sites.
                </p>

                <p>
                    J’ai écrit un article <a href="https://flus.io/carnet/tarification-viser-juste.html">
                    pour expliquer le choix de cette tarification</a>.
                </p>

                <?php if ($this->registration_opened) { ?>
                    <p class="center">
                        <a class="btn btn-important" href="<?= _url('auth', 'register') ?>">
                            Inscrivez-vous, le 1<sup>er</sup> mois est gratuit
                        </a>
                    </p>
                <?php } ?>
             </div>
        </div>
    </section>

    <section class="fl-section fl-section-freshrss">
        <div class="fl-columns">
            <div class="fl-column">
                <h2>Flus utilise FreshRSS</h2>

                <p>
                    Quoi de mieux pour avoir confiance dans le service utilisé qu’<strong>un
                    logiciel dont le code est ouvert et amélioré par une communauté&nbsp;?</strong>
                </p>

                <p>
                    J’ai fait le choix d’utiliser <a href="https://freshrss.org">FreshRSS</a>
                    qui est une solution facile à prendre en main, solide et
                    efficace. Sa communauté réactive est toujours à l’écoute des
                    suggestions d’amélioration ce qui garantit des évolutions fréquentes.
                    Par ailleurs, <a href="https://github.com/flusio">l’ensemble de mes améliorations sont ouvertes</a>.
                </p>

                <p>
                    Petit bonus&nbsp;: j’ai été le principal mainteneur de FreshRSS
                    pendant des années, je connais donc le code comme ma poche.
                </p>

                <p class="lead">
                    Prendre un abonnement à Flus, <strong>c’est également
                    pérenniser mes contributions à un bien commun.</strong>
                </p>
            </div>

            <div class="fl-column fl-column-centered">
                <img class="logo" src="<?= Minz_Url::display('/themes/icons/icon.svg') ?>" />
            </div>
        </div>
    </section>

    <section class="fl-section fl-section-carnet">
        <p class="lead center">
            Vous voulez en savoir plus sur le service&nbsp;?<br />
            <strong><a href="https://flus.io/carnet/">Rendez-vous sur le blog «&nbsp;carnet de flus&nbsp;»</a></strong>
        </p>
    </section>

    <section class="fl-section fl-text-container">
        <h2>Flus, c’est qui&nbsp;? c’est quoi&nbsp;?</h2>

        <p>
            Derrière Flus, il y a une personne&nbsp;: Marien. Je fais partie de
            la vaste communauté du logiciel libre depuis bientôt 10 ans, dont 5
            passées au sein <a href="https://framasoft.org">de l’association
            Framasoft</a>.
        </p>

        <p>
            Mon parcours m’a permis de prendre conscience des enjeux politiques
            du numérique (surveillance, vie privée, etc.) Confier l’entièreté
            de ma vie en ligne à de gigantesques multi-nationales sans visage
            ne me convient pas. Le sujet du suivi de l’actualité me semble tout
            particulièrement sensible puisque c’est ce qui façonne notre vision
            et donc notre rapport au reste du monde.
        </p>

        <p>
            Je souhaite avoir, avec Flus, une démarche de proximité, de
            confiance et de transparence avec les usagers. Le service s’inscrit
            dans la démarche des <a href="https://chatons.org"><abbr>CHATONS</abbr></a>,
            bien que je n’en fasse pas (encore) partie&nbsp;; chaque chose en
            son temps.
        </p>

        <p>
            Il m’arrive également de blablater
            <a href="https://marienfressinaud.fr">sur mon site personnel</a> si
            vous souhaitez en savoir plus sur moi.
        </p>
    </section>
</main>

<footer class="fl-page-footer">
    <p class="center">
        <a href="?a=about">mentions légales</a>&nbsp;/&nbsp;<a href="https://status.flus.io/">statut du service</a>
    </p>
</footer>
