<?php FreshRSS::preLayout(); ?>
<!DOCTYPE html>
<html lang="<?php echo FreshRSS_Context::$user_conf->language; ?>" xml:lang="<?php echo FreshRSS_Context::$user_conf->language; ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <?php echo self::headStyle(); ?>
        <?php echo self::headScript(); ?>
        <link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="<?php echo Minz_Url::display('/favicon.ico'); ?>" />
        <link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="<?php echo Minz_Url::display('/themes/icons/favicon-256.png'); ?>" />
        <link rel="apple-touch-icon" href="<?php echo Minz_Url::display('/themes/icons/apple-touch-icon.png'); ?>" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="apple-mobile-web-app-title" content="<?php echo FreshRSS_Context::$system_conf->title; ?>">
        <meta name="msapplication-TileColor" content="#FFF" />
        <?php echo self::headTitle(); ?>
        <meta name="description" content="<?php echo htmlspecialchars(FreshRSS_Context::$name . ' | ' . FreshRSS_Context::$description, ENT_COMPAT, 'UTF-8'); ?>" />
    </head>

    <body>
        <header class="fl-page-header">
            <nav>
                <a class="fl-page-header-brand" href="<?= _url('index', 'index') ?>">
                    <img class="fl-page-header-logo" src="<?php echo _i('icon', true); ?>" alt="" />
                    Flus
                </a>

                <a href="<?= _url('auth', 'login') ?>">
                    Se connecter
                </a>
            </nav>
        </header>
<?php
flush();
$this->render();
?>
    </body>
</html>
