<?php if (isset($this->checkout_session_id)) { ?>
    <p>
        Vous allez être redirigé vers Stripe dans quelques secondes, veuillez patienter…
    </p>

    <p id="stripe-error">
    </p>

    <script>
        window.setTimeout(function() {
            var stripe = Stripe('<?= $this->stripe_public_key ?>');
            stripe.redirectToCheckout({
                sessionId: '<?= $this->checkout_session_id ?>',
            }).then(function (result) {
                document.getElementById('stripe-error').innerText = result.error.message;
            });
        }, 3000);
    </script>
<?php } else { ?>
    <p>
        Une erreur est survenue, étiez-vous en train de réaliser un paiement ?
    </p>

    <p>
        <a href="<?= _url('billing', 'index') ?>">Retour à la facturation</a>
    </p>

    <p>
        <a class="btn" href="mailto:support@flus.io">Prévenir le support</a>
    </p>
<?php } ?>
