<?php
    if (!$this->subscription_is_overdue) {
        $this->partial('aside_configure');
    }
?>

<div class="post">
    <h1>Facturation</h1>

    <form class="fl-renew-form" method="POST">
        <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

        <div class="form-group form-group-radios">
            <div class="group-name">
                Renouveler pour
            </div>

            <div class="group-controls">
                <label for="month-frequency">
                    <input
                        type="radio"
                        name="frequency"
                        id="month-frequency"
                        value="month"
                        <?php echo $this->subscription_frequency === 'month' ? 'checked' : ''; ?>
                    />
                    1 mois
                </label>

                <label for="year-frequency">
                    <input
                        type="radio"
                        name="frequency"
                        id="year-frequency"
                        value="year"
                        <?php echo $this->subscription_frequency === 'year' ? 'checked' : ''; ?>
                    />
                    1 an
                </label>
            </div>
        </div>

        <div class="form-group fl-renew-form-amount">
            <div class="group-name">
                soit
            </div>

            <div class="group-controls">
                <strong id="renew-amount-month"><?php echo $this->month_price; ?> €</strong>
                <strong id="renew-amount-year"><?php echo $this->year_price; ?> €</strong>
                à payer
            </div>
        </div>

        <div class="form-group">
            <div class="group-controls">
                <p>
                    Vous serez facturé à l’adresse suivante&nbsp;:
                </p>

                <address>
                    <?= $this->address['first_name'] . ' ' . $this->address['last_name'] ?><br />
                    <?= $this->address['address'] ?><br />
                    <?= $this->address['postcode'] . ' ' . $this->address['city'] ?>
                    <?php if ($this->address['country'] === 'BE'): ?>
                        <br />Belgique
                    <?php endif; ?>
                </address>

                <a href="<?= _url('billing', 'address') ?>">Modifier</a>
            </div>
        </div>

        <div class="form-group">
            <div class="group-controls">
                <p>
                    En validant ce formulaire, vous acceptez les
                    <a href="?a=cgv">Conditions Générales de Vente</a>
                    (<abbr>CGV</abbr>) du site.
                </p>

                <p>
                    Vous allez également être redirigé vers <a href="https://stripe.com/fr/">Stripe</a>,
                    le prestataire qui s’occupe de gérer les paiements.
                </p>
            </div>
        </div>

        <div class="form-group form-actions">
            <div class="group-controls">
                <button type="submit" class="btn btn-important">
                    Payer l’abonnement
                </button>

                <a class="btn" href="<?php echo _url('billing', 'index'); ?>">
                    Annuler
                </a>
            </div>
        </div>
    </form>
</div>
