<?php
    if (!$this->subscription_is_overdue) {
        $this->partial('aside_configure');
    }
?>

<div class="post">
    <?php if ($this->payment['completed_at']) { ?>
        <h1>Validation du paiement</h1>

        <p>
            Votre paiement a été validé et nous vous en remercions.
            Votre abonnement a par conséquent été prolongé
            <?= $this->payment['frequency'] === 'month' ? 'd’un mois.' : 'd’une année.' ?>
        </p>

    <?php } else { ?>
        <h1>Prise en compte du paiement</h1>

        <p>
            Votre paiement a été pris en compte, mais nous attendons la
            confirmation que celui-ci s’est bien passé.
        </p>

        <p>
            <a class="btn" href="<?= _url('billing', 'success') ?>">Rafraîchir la page</a>
        </p>
    <?php } ?>

    <p>
        <a href="<?= _url('billing', 'index') ?>">← Retour à la facturation</a>
    </p>
</div>
